import os
from fpdf import FPDF

class OdishaItineraryPDF(FPDF):
    def header(self):
        # Premium branding banner
        self.set_fill_color(224, 122, 95)  # Terracotta Orange
        self.rect(0, 0, 210, 40, "F")
        
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.ln(10) # padding instead of cell
        self.cell(0, 10, "ODISHA TOURISM EXPLORER", align="C")
        self.ln(10)
        
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 5, "Your Custom Local Retrieval-Augmented Travel Guide", align="C")
        self.ln(15)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, "Odisha Tourism Local Agent - 'India's Best Kept Secret' | Page " + str(self.page_no()), align="C")

def generate_itinerary_pdf(itinerary_text, filename, duration_days="3 Days", traveler_name="Explorer"):
    """
    Generates a beautifully structured PDF itinerary from a text block.
    """
    pdf = OdishaItineraryPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Reset text color to deep charcoal
    pdf.set_text_color(61, 64, 91)
    
    # Metadata Box
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(244, 241, 222)  # Soft sand cream
    pdf.cell(0, 8, " TRIP METADATA", fill=True)
    pdf.ln(8)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"  Prepared For: {traveler_name}", fill=True)
    pdf.ln(6)
    pdf.cell(0, 6, f"  Duration: {duration_days}", fill=True)
    pdf.ln(6)
    pdf.cell(0, 6, f"  Generated By: Local Odisha AI RAG Agent", fill=True)
    pdf.ln(14)
    
    # Split text into sections or lines to print cleanly
    pdf.set_font("Helvetica", "", 10.5)
    
    lines = itinerary_text.split('\n')
    for line in lines:
        cleaned_line = line.encode('latin-1', 'replace').decode('latin-1') # Sanitize to avoid PDF encoding issues
        
        if cleaned_line.strip().startswith("Day") or cleaned_line.strip().startswith("DAY"):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(224, 122, 95) # Terracotta highlight for days
            pdf.cell(0, 8, cleaned_line)
            pdf.ln(8)
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(61, 64, 91)
        elif cleaned_line.strip().startswith("#") or cleaned_line.strip().startswith("##"):
            pdf.ln(3)
            # Remove Markdown hash marks
            clean_hdr = cleaned_line.replace("#", "").strip()
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(212, 175, 55) # Marigold Gold
            pdf.cell(0, 8, clean_hdr)
            pdf.ln(8)
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(61, 64, 91)
        elif cleaned_line.strip().startswith("-") or cleaned_line.strip().startswith("*"):
            # Bullet point alignment
            pdf.set_font("Helvetica", "", 10.5)
            bullet_text = "  " + cleaned_line.strip()
            pdf.multi_cell(0, 6, bullet_text)
        else:
            if cleaned_line.strip() == "":
                pdf.ln(2)
            else:
                pdf.multi_cell(0, 6, cleaned_line)
                
    # Save the PDF to file
    try:
        pdf.output(filename)
        return True
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return False
